### ISSUE TITLE
findResultsCount

### ISSUE THREAD

**Issue by javid-abd** [stephanrauh/ExploringAngular#1]
Is it possible to add this functionality? It doesn't show the matches right now (for example 3 of 10 matches)

https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by stephanrauh** [comment]
I've moved your ticket to https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/4.

As for your question: I'm sure it's possible. Maybe it's simply a matter of updating to the current release of Mozilla's pdf.js library. Please follow the progress in the new ticket.
