### ISSUE TITLE
Need to show one page at the time

### ISSUE THREAD

**Issue by Vigneshjana** [stephanrauh/ExploringAngular#3]
Need to show one page at the time after clicking next button only i need to show the another page is it possible?
and also i need to use hotkeys for page next,page down,zoom in,zoom out

**Comment by stephanrauh** [comment]
I'll care about this ticket at the main repository of `<ngx-extended-pdf-viewer>`. So don't be confused by me closing this ticket: it's still open. I've even split it into two tickets. :)
