### ISSUE TITLE
How to highlight text (text entered through input)/ group of words/ or many words in the pdf

### ISSUE THREAD

**Issue by Rambj** [stephanrauh/ExploringAngular#4]
Hi Stephanrauh,
I want to highlight the text in PDF in angular. By using ngx-extended-pdf-viewer, how can I highlight text (text entered through input)/ group of words/ or many words in the pdf.

Thanks in Advance.. 

Ramarao

**Comment by stephanrauh** [comment]
Are you looking for the find service? I've described it here: http://pdfviewer.net/find

**Comment by stephanrauh** [comment]
BTW: if you're still missing the feature, please open the bug at https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues. It's easier to track bug if they are reported at one place only.
